const cardsInfo = {
  bobbyHull: {
    id: 1,
    name: "Robert Marvin Hull",
    shortname: "Bobby Hull",
    nickname: "The Golden Jet",
    born: "Point Anne, ON, Canada",
    position: "Left Wing",
    url: "../assets/pictures/cropped/bobby-hull.jpeg",
  },
  bobbyOrr: {
    id: 2,
    name: "Robert Gordon Orr",
    shortname: "Bobby Orr",
    nickname: "Number 4",
    born: "Parry Sound, ON, Canada",
    position: "Defense",
    url: "/assets/pictures/cropped/bobby-orr.jpeg",
  },
  gordieHowe: {
    id: 3,
    name: "Gordon 'Gordie' Howe",
    shortname: "Gordie Howe",
    nickname: "Mr. Hockey",
    born: "Floral, SK, Canada",
    position: "Right Wing",
    url: "/assets/pictures/cropped/gordie-howe.jpeg",
  },
  guyLafleur: {
    id: 4,
    name: "Guy Damien Lafleur",
    shortname: "Guy Lafleur",
    nickname: "The Flower",
    born: "Thurso, QC, Canada",
    position: "Right Wing",
    url: "/assets/pictures/cropped/guy-lafleur.jpeg",
  },
  henriRichard: {
    id: 5,
    name: "Joseph Henri Richard",
    shortname: "Henri Richard",
    nickname: "Pocket Rocket",
    born: "Montreal, QC, Canada",
    position: "Centre",
    url: "/assets/pictures/cropped/henri-richard.jpeg",
  },
  joeSakic: {
    id: 6,
    name: "Joseph Steven Sakic",
    shortname: "Joe Sakic",
    nickname: "Burnaby Joe",
    born: "Burnaby, BC, Canada",
    position: "Center",
    url: "/assets/pictures/cropped/joe-sakic.jpeg",
  },
  jonathanToews: {
    id: 7,
    name: "Jonathan Bryan Toews",
    shortname: "Jonathan Toews",
    nickname: "Captain Serious",
    born: "Winnipeg, MB, Canada",
    position: "Centre",
    url: "/assets/pictures/cropped/jonathan-toews.jpeg",
  },
  marioLemieux: {
    id: 8,
    name: "Joseph Mario Lemieux",
    shortname: "Mario Lemieux",
    nickname: "The Magnificent One",
    born: "Montreal, QC, Canada",
    position: "Centre",
    url: "/assets/pictures/cropped/mario-lemieux.jpeg",
  },
  markMessier: {
    id: 9,
    name: "Mark John Douglas Messier",
    shortname: "Mark Messier",
    nickname: "The Moose",
    born: "St. Albert, AB, Canada",
    position: "Centre",
    url: "/assets/pictures/cropped/mark-messier.jpeg",
  },
  martinBrodeur: {
    id: 10,
    name: "Martin Pierre Brodeur",
    shortname: "Martin Brodeur",
    nickname: "Marty Brody",
    born: "Montreal, QC, Canada",
    position: "Goalie",
    url: "/assets/pictures/cropped/martin-brodeur-2013.jpeg",
  },
  mauriceRichard: {
    id: 11,
    name: "Joseph Henri Maurice Richard",
    shortname: "Maurice Richard",
    nickname: "The Rocket",
    born: "Montreal, QC, Canada",
    position: "Right Wing",
    url: "/assets/pictures/cropped/maurice-richard.jpeg",
  },
  patrickRoy: {
    id: 12,
    name: "Patrick Jacques Roy",
    shortname: "Patrick Roy",
    nickname: "Saint Patrick",
    born: "Quebec City, QC, Canada",
    position: "Goalie",
    url: "/assets/pictures/cropped/patrick-roy.jpeg",
  },
  philEsposito: {
    id: 13,
    name: "Philip Anthony Esposito",
    shortname: "Phil Esposito",
    nickname: "Espo",
    born: "Sault Ste. Marie, ON, Canada",
    position: "Centre",
    url: "/assets/pictures/cropped/phil-esposito.jpeg",
  },
  sidneyCrosby: {
    id: 14,
    name: "Sidney Patrick Crosby",
    shortname: "Sidney Crosby",
    nickname: "Sid The Kid",
    born: "Halifax, NS, Canada",
    position: "Centre",
    url: "/assets/pictures/cropped/sidney-crosby.jpeg",
  },
  steveYzerman: {
    id: 15,
    name: "Stephen Gregory Yzerman",
    shortname: "Stephen Yzerman",
    nickname: "The Captain",
    born: "Cranbrook, BC, Canada",
    position: "Centre",
    url: "/assets/pictures/cropped/steve-yzerman.jpeg",
  },
  wayneGretzky: {
    id: 16,
    name: "Wayne Douglas Gretzky",
    shortname: "Wayne Gretzky",
    nickname: "The Great One",
    born: "Brantford, ON, Canada",
    position: "Centre",
    url: "/assets/pictures/cropped/wayne-gretzky-1981.jpeg",
  },
};

export default cardsInfo;
